[build]
phpExtensions = ["gd"]

[deploy]
startCommand = "php artisan config:clear && php artisan migrate --force && php artisan db:seed --class=AdminSeeder --force && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT"

